version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_DB=boilerplate
      - POSTGRES_USER=boiler
      - POSTGRES_PASSWORD=boiler123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  api:
    container_name: boilerplate-container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
